### PR TITLE
Ada 26 master

### PR DESCRIPTION
**Pull request by cachemeifyoucan0**
business logic for a member recording attendance

testing backend:

in postman: 
- run the app `npm run dev`
- create a meeting in the database that has an event code, since this code assumes that exists 
- now go to postman and hit the endpoint "http://localhost:3000/api/attendance/record"
- no need to create a new student if the one you are testing doesn't exist, this covers that
- body should be of the form: `{"event_code": "", 
"f_name": "",
"l_name_dot_num": "",
"year_level": ""}`
- send

**testing both fe & be:**

in web dev:
- create a meeting in the database that has an event code, since this code assumes that exists 
- go to "https://dev-ada.herokuapp.com/attendance"
- fill out the form with the code created and submit
- check database to see if successful created new student if needed and to meeting_student table

### CODE REVIEW

**Review by jgeorge37 — CHANGES_REQUESTED** [review]
This needs to be tested in the dev environment https://dev-ada.herokuapp.com - I got an error when I tried to submit attendance there

**Comment by jgeorge37** [comment]
In the console: Failed to load resource: the server responded with a status of 500 (Internal Server Error) from api/attendance

**Comment by cachemeifyoucan0** [comment]
> This needs to be tested in the dev environment https://dev-ada.herokuapp.com - I got an error when I tried to submit attendance there

my b my b that's the link i meant for dev 🤯

**Comment by cachemeifyoucan0** [comment]
> In the console: Failed to load resource: the server responded with a status of 500 (Internal Server Error) from api/attendance

did the event code exist?

**Comment by jgeorge37** [comment]
> > In the console: Failed to load resource: the server responded with a status of 500 (Internal Server Error) from api/attendance
> 
> did the event code exist?

yes

**Comment by cachemeifyoucan0** [comment]
> > > In the console: Failed to load resource: the server responded with a status of 500 (Internal Server Error) from api/attendance
> > 
> > 
> > did the event code exist?
> 
> yes

balls. hold up

**Comment by cachemeifyoucan0** [comment]
ok thanks to @smiskus second pair of eyes it should be good now, but I changed it back to dev again lmao @jgeorge37

**Review by jgeorge37 — APPROVED** [review]

**Pull request merged**
