### PR TITLE
ADA-35 created sponsorship table

### PR DESCRIPTION
**Pull request by cachemeifyoucan0**
I wanted to use ENUMs but was getting a depreciation warning lol - definitely open to other ideas on how to handle tires/status if you want to check out the comments

how to test:
`git pull`
`git checkout ADA-35`
on the root directory `npm run migrate`
and check out the sponsorship table successfully shows up in your postgresql local or pdadmin local

NOTE: I know this is named the same as @jgeorge37 recent database PR but we figure this might be easier to merge first

### CODE REVIEW

**Review by jgeorge37 — COMMENTED** [review]
Can you get rid of the commented out code and also I think it would be better to have one tier varchar column incase we rename/add/remove tiers over time

**Comment by cachemeifyoucan0** [comment]
> Can you get rid of the commented out code and also I think it would be better to have one tier varchar column incase we rename/add/remove tiers over time

sure, I just wanted it as a reference

I just thought a varchar would be rlly error prone - could we maybe do like a 1 2 3 INT? unless you think varchar would be ok

**Comment by jgeorge37** [comment]
I think varchar would be ok since we wouldn't let the user mess with it with whatever text they want, like if we implemented getting sponsors by tier we could use a dropdown and have control over the options

**Comment by cachemeifyoucan0** [comment]
> I think varchar would be ok since we wouldn't let the user mess with it with whatever text they want, like if we implemented getting sponsors by tier we could use a dropdown and have control over the options

ok updated !

**Review by SnobbyDragon — COMMENTED** [review]
IT'S WORKING :))))))))))))

**Review by SnobbyDragon — APPROVED** [review]
boom.

**Pull request merged**
