### PR TITLE
Ada 26 - attendance business logic

### PR DESCRIPTION
**Pull request by cachemeifyoucan0**
to test:

- create a meeting in the database that has an event code, since this ticket assumes that exists (can do this by logging into exec and clicking on meetings, and creating one or selecting one that's there)
- go to "https://dev-ada.herokuapp.com/attendance"
- fill out the form with the code created and submit
- check database to see if successful created new student if needed and to meeting_student table

### CODE REVIEW

**Comment by jgeorge37** [comment]
Getting a 500 internal server error in the console when I submit for an existing student, for a second meeting. Meeting code exists (triple checked). Attendance is not recorded and no update is made to the student record in this case.

**Review by jgeorge37 — CHANGES_REQUESTED** [review]
see previous comment

**Comment by cachemeifyoucan0** [comment]
> Getting a 500 internal server error in the console when I submit for an existing student, for a second meeting. Meeting code exists (triple checked). Attendance is not recorded and no update is made to the student record in this case. I would recommend testing in the development environment even if it works locally before opening a master pr

I haven't been able to see the attendance codes on dev, the forgot password is not sending mason.906 a link 😞 I'm sorry should that email be working?

**Comment by cachemeifyoucan0** [comment]
> Getting a 500 internal server error in the console when I submit for an existing student, for a second meeting. Meeting code exists (triple checked). Attendance is not recorded and no update is made to the student record in this case. I would recommend testing in the development environment even if it works locally before opening a master pr

This is working for me (added myself to meeting sloth yoga (99435) and goat yoga (73062)) did maybe the hot fix also fix this? def want to double check though

**Comment by jgeorge37** [comment]
This still does not work if I submit attendance for the same student for two meetings and give a different school level.

**Review by jgeorge37 — CHANGES_REQUESTED** [review]
see previous comment

**Comment by jgeorge37** [comment]
there is still a 500 error in the console coming from the attendance API and nothing is stored in the DB on the second submission

**Pull request closed without merging**
